name: Deployment

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: npm install
        env:
          CI: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER}}
          key: ${{ secrets.KEY}}
          port: ${{ secrets.PORT}}
          script: |
            set -e
            nvm install 16
            cd $HOME/node-deploy-cicd-aws
            git fetch --all
            git reset --hard origin/master
            npm install
            pm2 restart node-deploy-cicd-aws
